### ISSUE TITLE
AttributeError: 'ZStage' object has no attribute 'move_to'

### ISSUE THREAD

**Issue by ryanfobel** [wheeler-microfluidics/microdrop.mr-box-plugin#2]
# Traceback

```python
2017-08-03 15:03:39 [ERROR:mr_box_peripheral_board_plugin]: [mr_box_peripheral_board_plugin] Error applying step options.
Traceback (most recent call last):
  File "C:\Users\Ryan\MicroDrop\etc\microdrop\plugins\enabled\mr_box_peripheral_board_plugin\__init__.py", line 100, in apply_step_options
    self.board.zstage.move_to(position)
AttributeError: 'ZStage' object has no attribute 'move_to'
```

# Fix

The correct call is: `self.board.zstage_move_to(position)`, but we also need to enable/disable the motor. We can either do this in the plugin itself (.e.g., `proxy.zstage.motor_enabled = True/False`) or we could enable/disable it automatically within the firmware's `zstage_move_to()` method.

**Comment by cfobel** [comment]
This issue was caused by the fact that I commits that I hadn't yet published.

As of [`v0.6`][1] (available for install from the `wheeler-microfluidics` Conda channel), the `Proxy.Zstage.move_to(position)` method exists.  This method does take care of enabling and disabling the motor before and after the `move_to` call.

The reason why this wasn't implemented directly in the C++ firmware was that I wasn't sure if there might be a use case where the motor should be left engaged, e.g., to forcibly hold the motor's position.  Since then I've done some empirical testing and it seems like the z-stage is working ok without leaving the motor engaged when not moving, so perhaps we can move the motor enabling/disabling into the firmware...

[1]: https://github.com/wheeler-microfluidics/mr-box-peripheral-board.py/releases/tag/v0.6

**Comment by ryanfobel** [comment]
So we can close this issue then?
